Repository jenkinsci/slack-plugin, pull requests merged in 2019-09, with the labels that each got.

#621 Update Pom URL to GitHub
  pom.xml
Labels: size/XS

#624 Force jenkins-ci hook when base url mis-configured
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/test/java/jenkins/plugins/slack/StandardSlackServiceTest.java
Labels: feature

#626 Fix null pointer
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
Labels: fix

#629 BOM 3
  pom.xml
Labels: size/XS
