Repository jenkinsci/slack-plugin, pull requests merged in 2019-04, with the labels that each got.

#549 Add release drafter
  release-drafter.yml
Labels: chore

#550 Add ISSUE TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: chore

#548 Add import order checkstyle rules
  checkstyle.xml
  pom.xml
  src/main/java/jenkins/plugins/slack/ActiveNotifier.java
  src/main/java/jenkins/plugins/slack/CredentialsObtainer.java
  src/main/java/jenkins/plugins/slack/JenkinsTokenExpander.java
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/config/GlobalCredentialMigrator.java
  src/main/java/jenkins/plugins/slack/decisions/Condition.java
  src/main/java/jenkins/plugins/slack/decisions/Context.java
  src/main/java/jenkins/plugins/slack/decisions/NotificationConditions.java
  src/main/java/jenkins/plugins/slack/logging/SlackNotificationsLogger.java
  src/main/java/jenkins/plugins/slack/webhook/CommandRouter.java
  src/main/java/jenkins/plugins/slack/webhook/GetProjectLogCommand.java
  src/main/java/jenkins/plugins/slack/webhook/GlobalConfig.java
  src/main/java/jenkins/plugins/slack/webhook/ListProjectsCommand.java
  src/main/java/jenkins/plugins/slack/webhook/WebhookEndpoint.java
  src/main/java/jenkins/plugins/slack/webhook/model/JsonResponse.java
  src/main/java/jenkins/plugins/slack/webhook/model/SlackTextMessage.java
  src/main/java/jenkins/plugins/slack/workflow/SlackResponse.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/Messages.properties
  src/test/java/jenkins/plugins/slack/CloseableHttpResponseStub.java
  src/test/java/jenkins/plugins/slack/MessageBuilderEscapeTest.java
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
  src/test/java/jenkins/plugins/slack/config/GlobalCredentialMigratorTest.java
  src/test/java/jenkins/plugins/slack/decisions/NotificationConditionsTest.java
  src/test/java/jenkins/plugins/slack/logging/SlackNotificationsLoggerTest.java
  src/test/java/jenkins/plugins/slack/webhook/WebhookEndpointTest.java
  src/test/java/jenkins/plugins/slack/workflow/MessageBuilderTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: chore

#552 Make bot messages respect the message parameter
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
Labels: fix

#547 Adding support for configuring when matrix projects notify.
  pom.xml
  src/main/java/jenkins/plugins/slack/ActiveNotifier.java
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/config/GlobalCredentialMigrator.java
  src/main/java/jenkins/plugins/slack/matrix/MatrixTriggerMode.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/Messages.properties
  src/main/resources/jenkins/plugins/slack/SlackNotifier/config.jelly
  src/main/webapp/help-matrixTriggerMode.html
  src/test/java/jenkins/plugins/slack/ActiveNotifierTest.java
  src/test/java/jenkins/plugins/slack/SlackNotifierStub.java
  src/test/java/jenkins/plugins/slack/SlackNotifierUnitTest.java
  src/test/java/jenkins/plugins/slack/config/GlobalCredentialMigratorTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepIntegrationTest.java
Labels: fix

#553 Make matrix plugin optional
  pom.xml
  src/main/java/jenkins/plugins/slack/SlackMatrixBridge.java
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
  src/test/java/jenkins/plugins/slack/SlackNotifierUnitTest.java
Labels: enhancement

#555 Update dependencies
  pom.xml
Labels: chore

#562 👶 badger whoopsie 🐤
  README.md
Labels: chore
