Repository jenkinsci/slack-plugin, pull requests merged in 2019-06, with the labels that each got.

#581 Fix false success on test connection with bot user
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
Labels: fix

#582 Add missing configuration as code test
  pom.xml
  src/test/java/jenkins/plugins/slack/jcasc/ConfigurationAsCodeTest.java
  src/test/resources/jenkins/plugins/slack/jcasc/configuration-as-code-expected.yml
  src/test/resources/jenkins/plugins/slack/jcasc/configuration-as-code.yml
Labels: test

#585 Fix threading
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
Labels: fix

#587 Adding UTF-8 encoding to StringEntity
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
Labels: fix

#588 Always set the Content-Type Header
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
Labels: enhancement
