Repository jenkinsci/slack-plugin, pull requests merged in 2019-08, with the labels that each got.

#602 Simplify ui
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/webhook/GlobalConfig.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/Messages.properties
  src/main/resources/jenkins/plugins/slack/SlackNotifier/config.jelly
  src/main/resources/jenkins/plugins/slack/SlackNotifier/global.jelly
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-authToken.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-baseUrl.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-botUser.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-customMessage.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-iconEmoji.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-room.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-sendAsText.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-teamDomain.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-tokenCredentialId.html
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-username.html
  src/main/resources/jenkins/plugins/slack/workflow/SlackSendStep/config.jelly
  src/main/resources/jenkins/plugins/slack/workflow/SlackSendStep/help-botUser.html
  src/main/webapp/help-globalConfig-iconEmoji.html
  src/main/webapp/help-globalConfig-slackBuildServerUrl.html
  src/main/webapp/help-globalConfig-slackTeamDomain.html
  src/main/webapp/help-globalConfig-tokenCredentialId.html
  src/main/webapp/help-projectConfig-slackRoom.html
  src/main/webapp/help-projectConfig-slackToken.html
  src/main/webapp/help.html
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepIntegrationTest.java
Labels: enhancement

#600 Support for notifying commit authors by direct message
  pom.xml
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/SlackNotifierBuilder.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/StandardSlackServiceBuilder.java
  src/main/java/jenkins/plugins/slack/user/EmailSlackUserIdResolver.java
  src/main/java/jenkins/plugins/slack/user/NoSlackUserIdResolver.java
  src/main/java/jenkins/plugins/slack/user/SlackUserIdResolver.java
  src/main/java/jenkins/plugins/slack/user/SlackUserIdResolverDescriptor.java
  src/main/java/jenkins/plugins/slack/user/SlackUserProperty.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/Messages.properties
  src/main/resources/jenkins/plugins/slack/SlackNotifier/global.jelly
  src/main/resources/jenkins/plugins/slack/user/EmailSlackUserIdResolver/help.html
  src/main/resources/jenkins/plugins/slack/user/NoSlackUserIdResolver/help.html
  src/main/resources/jenkins/plugins/slack/user/SlackUserProperty/config.jelly
  src/main/resources/jenkins/plugins/slack/user/SlackUserProperty/help-disableNotifications.html
  src/main/resources/jenkins/plugins/slack/user/SlackUserProperty/help-userId.html
  src/main/resources/jenkins/plugins/slack/workflow/SlackSendStep/config.jelly
  src/main/resources/jenkins/plugins/slack/workflow/SlackSendStep/help-notifyCommitters.html
  src/test/java/jenkins/plugins/slack/CloseableHttpClientStub.java
  src/test/java/jenkins/plugins/slack/CloseableHttpResponseStub.java
  src/test/java/jenkins/plugins/slack/EmailSlackUserIdResolverTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
  src/test/resources/jenkins/plugins/slack/lookUpByEmailResponseError.json
  src/test/resources/jenkins/plugins/slack/lookUpByEmailResponseOK.json
Labels: feature

#604 Add jcasc docs link
  README.md
Labels: chore, size/XS

#603 Add bom and cleanup pom
  pom.xml
  src/test/java/jenkins/plugins/slack/ActiveNotifierTest.java
  src/test/java/jenkins/plugins/slack/MessageBuilderEscapeTest.java
  src/test/java/jenkins/plugins/slack/webhook/WebhookEndpointTest.java
  src/test/java/jenkins/plugins/slack/workflow/MessageBuilderTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: chore, size/M

#608 Add request timeout
  Jenkinsfile
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
Labels: fix

#606 Bump plugin baseline to 2.164.3 and code cleanup
  Jenkinsfile
  checkstyle.xml
  pom.xml
  src/main/java/jenkins/plugins/slack/ActiveNotifier.java
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/SlackNotifierBuilder.java
  src/main/java/jenkins/plugins/slack/matrix/MatrixTriggerMode.java
  src/main/java/jenkins/plugins/slack/user/SlackUserIdResolverDescriptor.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/user/SlackUserProperty/config.jelly
  src/test/java/jenkins/plugins/slack/CloseableHttpClientStub.java
  src/test/java/jenkins/plugins/slack/CloseableHttpResponseStub.java
  src/test/java/jenkins/plugins/slack/EmailSlackUserIdResolverTest.java
  src/test/java/jenkins/plugins/slack/MessageBuilderEscapeTest.java
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: chore

#610 Fix finding credential
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
Labels: fix

#611 Java 11 test fix and enable CI
  Jenkinsfile
  src/spotbugs/excludesFilter.xml
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: chore

#612 Add support for blocks
  README.md
  src/main/java/jenkins/plugins/slack/SlackRequest.java
  src/main/java/jenkins/plugins/slack/SlackService.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: enhancement

#613 Remove slack outgoing webhook functionality
  pom.xml
  src/main/java/jenkins/plugins/slack/webhook/CommandRouter.java
  src/main/java/jenkins/plugins/slack/webhook/GetProjectLogCommand.java
  src/main/java/jenkins/plugins/slack/webhook/GlobalConfig.java
  src/main/java/jenkins/plugins/slack/webhook/ListProjectsCommand.java
  src/main/java/jenkins/plugins/slack/webhook/RouterCommand.java
  src/main/java/jenkins/plugins/slack/webhook/ScheduleJobCommand.java
  src/main/java/jenkins/plugins/slack/webhook/SlackRouterCommand.java
  src/main/java/jenkins/plugins/slack/webhook/WebhookEndpoint.java
  src/main/java/jenkins/plugins/slack/webhook/exception/CommandRouterException.java
  src/main/java/jenkins/plugins/slack/webhook/exception/RouteNotFoundException.java
  src/main/java/jenkins/plugins/slack/webhook/model/JsonResponse.java
  src/main/java/jenkins/plugins/slack/webhook/model/SlackPostData.java
  src/main/java/jenkins/plugins/slack/webhook/model/SlackTextMessage.java
  src/main/java/jenkins/plugins/slack/webhook/model/SlackWebhookCause.java
  src/main/resources/jenkins/plugins/slack/webhook/GlobalConfig/config.groovy
  src/main/resources/jenkins/plugins/slack/webhook/GlobalConfig/help-slackOutgoingWebhookToken.html
  src/main/resources/jenkins/plugins/slack/webhook/GlobalConfig/help-slackOutgoingWebhookURL.html
  src/test/java/jenkins/plugins/slack/webhook/WebhookEndpointTest.java
Labels: breaking

#614 Add slackUploadFile step
  README.md
  pom.xml
  src/main/java/jenkins/plugins/slack/CredentialsObtainer.java
  src/main/java/jenkins/plugins/slack/HttpClient.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackFileRequest.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUploadFileRunner.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUploadFileStep.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/Messages.properties
  src/main/resources/jenkins/plugins/slack/pipeline/SlackUploadFileStep/config.jelly
  src/main/resources/jenkins/plugins/slack/pipeline/SlackUploadFileStep/help-channel.html
  src/main/resources/jenkins/plugins/slack/pipeline/SlackUploadFileStep/help-credentialId.html
  src/main/resources/jenkins/plugins/slack/pipeline/SlackUploadFileStep/help-filePath.html
  src/main/resources/jenkins/plugins/slack/pipeline/SlackUploadFileStep/help-initialComment.html
  src/test/java/jenkins/plugins/slack/pipeline/SlackUploadFileStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: enhancement

#617 Incrementalified
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore, size/S
