Repository jenkinsci/slack-plugin, pull requests merged in 2020-03, with the labels that each got.

#674 Update README for Create your app
  README.md
Labels: size/S

#676 use apache httpcomponents client api plugin
  pom.xml
Labels: dependencies, size/S

#679 Add support for updating a previous message.
  README.md
  src/main/java/jenkins/plugins/slack/SlackRequest.java
  src/main/java/jenkins/plugins/slack/SlackService.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/StandardSlackServiceBuilder.java
  src/main/java/jenkins/plugins/slack/workflow/SlackSendStep.java
  src/main/resources/jenkins/plugins/slack/Messages.properties
  src/main/resources/jenkins/plugins/slack/workflow/SlackSendStep/help-timestamp.html
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
  src/test/java/jenkins/plugins/slack/StandardSlackServiceTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: enhancement

#682 add OnRegression NotificationConditions
  src/main/java/jenkins/plugins/slack/ActiveNotifier.java
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/decisions/Context.java
  src/main/java/jenkins/plugins/slack/decisions/NotificationConditions.java
  src/main/java/jenkins/plugins/slack/decisions/OnRegression.java
  src/test/java/jenkins/plugins/slack/decisions/OnRegressionTest.java
Labels: bug

#675 Enable use system properties on http client - fixes tls 1.2 issues in some cases
  src/main/java/jenkins/plugins/slack/HttpClient.java
  src/test/java/jenkins/plugins/slack/SlackApiTLSTest.java
Labels: fix
