Repository jenkinsci/slack-plugin, pull requests merged in 2020-05, with the labels that each got.

#692 Add mention of required oauth scopes for user id lookups
  README.md
Labels: size/XS

#695 Update 'Bot User' instructions to reflect changes
  README.md
Labels: size/M

#696 Follow the established exception handling convention.
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
Labels: bug
