Repository jenkinsci/slack-plugin, pull requests merged in 2020-07, with the labels that each got.

#709 Swap to release drafter GitHub action
  .github/workflows/release-drafter.yml
Labels: chore, size/S

#711 Add example of how to upload a file to a thread
  README.md
Labels: documentation, size/XS

#712 Pass checkstyle properties through
  pom.xml
Labels: chore, size/XS
