Repository jenkinsci/slack-plugin, pull requests merged in 2020-08, with the labels that each got.

#724 Add color information to README.md
  README.md
Labels: size/S

#723 Bump baseline to 2.222.x
  pom.xml
Labels: chore, size/S

#704 Added file upload functionality for freestyle jobs
  src/main/java/jenkins/plugins/slack/ActiveNotifier.java
  src/main/java/jenkins/plugins/slack/CredentialsObtainer.java
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/SlackNotifierBuilder.java
  src/main/java/jenkins/plugins/slack/SlackService.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/logging/BuildAwareLogger.java
  src/main/java/jenkins/plugins/slack/logging/SlackNotificationsLogger.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUploadFileRunner.java
  src/main/java/jenkins/plugins/slack/user/SlackUserIdResolver.java
  src/main/resources/index.jelly
  src/main/resources/jenkins/plugins/slack/SlackNotifier/config.jelly
  src/main/resources/jenkins/plugins/slack/SlackNotifier/help-artifactIncludes.html
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
Labels: enhancement
