Repository jenkinsci/slack-plugin, pull requests merged in 2024-06, with the labels that each got.

#976 Fix cleanChannelName() to return extracted `channel` even if channelName doesn't have `#` prefix
  src/main/java/jenkins/plugins/slack/pipeline/SlackUploadFileStep.java
Labels: bug, size/XS

#977 Modify `getChannelId` and `convertChannelNameToId` for efficient channel ID retrieval
  src/main/java/jenkins/plugins/slack/cache/SlackChannelIdCache.java
Labels: enhancement, size/M

#983 Enable Jenkins Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore, size/S
