Repository jenkinsci/slack-plugin, pull requests merged in 2024-08, with the labels that each got.

#992 Modernize to Jenkins 2.440.3
  pom.xml
Labels: size/XS, developer

#994 Update Jenkins Security Scan action
  .github/workflows/jenkins-security-scan.yml
Labels: size/XS

#996 Add MIT LICENSE file to project root
  LICENSE
Labels: size/S, documentation

#1004 Remove # consistently from channel name in file upload
  src/main/java/jenkins/plugins/slack/cache/SlackChannelIdCache.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUploadFileStep.java
Labels: bug, size/M
