Repository jenkinsci/slack-plugin, pull requests merged in 2025-01, with the labels that each got.

#1026 Use `jenkins.baseline` to reduce bom update mistakes
  pom.xml
Labels: chore, size/XS

#1028 Migrate from EE 8 to EE 9
  pom.xml
  src/main/java/jenkins/plugins/slack/SlackNotifier.java
  src/main/java/jenkins/plugins/slack/user/SlackUserProperty.java
Labels: size/S, developer, internal

#1030 Migrate to `httpclient5`
  pom.xml
  src/main/java/jenkins/plugins/slack/HttpClient.java
  src/main/java/jenkins/plugins/slack/NoProxyHostCheckerRoutePlanner.java
  src/main/java/jenkins/plugins/slack/StandardSlackService.java
  src/main/java/jenkins/plugins/slack/cache/SlackChannelIdCache.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUploadFileRunner.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUserIdFromEmailStep.java
  src/main/java/jenkins/plugins/slack/pipeline/SlackUserIdsFromCommittersStep.java
  src/main/java/jenkins/plugins/slack/user/EmailSlackUserIdResolver.java
  src/main/java/jenkins/plugins/slack/user/SlackUserIdResolver.java
  src/test/java/jenkins/plugins/slack/CloseableHttpClientStub.java
  src/test/java/jenkins/plugins/slack/CloseableHttpResponseStub.java
  src/test/java/jenkins/plugins/slack/SlackApiTLSTest.java
  src/test/java/jenkins/plugins/slack/StandardSlackServiceStub.java
  src/test/java/jenkins/plugins/slack/StandardSlackServiceTest.java
  src/test/java/jenkins/plugins/slack/user/EmailSlackUserIdResolverTest.java
  src/test/java/org/apache/hc/client5/http/impl/classic/CloseableHttpClientStub.java
  src/test/java/org/apache/hc/client5/http/impl/classic/CloseableHttpResponseStub.java
Labels: enhancement, size/XL

#1029 Migrate tests to JUnit5
  pom.xml
  src/test/java/jenkins/plugins/slack/MessageBuilderEscapeTest.java
  src/test/java/jenkins/plugins/slack/SlackApiTLSTest.java
  src/test/java/jenkins/plugins/slack/SlackNotifierTest.java
  src/test/java/jenkins/plugins/slack/SlackNotifierUnitTest.java
  src/test/java/jenkins/plugins/slack/StandardSlackServiceTest.java
  src/test/java/jenkins/plugins/slack/config/GlobalCredentialMigratorTest.java
  src/test/java/jenkins/plugins/slack/decisions/ContextTest.java
  src/test/java/jenkins/plugins/slack/decisions/NotificationConditionsTest.java
  src/test/java/jenkins/plugins/slack/decisions/OnBackToNormalTest.java
  src/test/java/jenkins/plugins/slack/decisions/OnEveryFailureTest.java
  src/test/java/jenkins/plugins/slack/decisions/OnRegressionTest.java
  src/test/java/jenkins/plugins/slack/decisions/OnRepeatedFailureTest.java
  src/test/java/jenkins/plugins/slack/decisions/OnSingleFailureTest.java
  src/test/java/jenkins/plugins/slack/jcasc/ConfigurationAsCodeTest.java
  src/test/java/jenkins/plugins/slack/logging/SlackNotificationsLoggerTest.java
  src/test/java/jenkins/plugins/slack/pipeline/SlackUploadFileStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/pipeline/SlackUserIdFromEmailStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/pipeline/SlackUserIdsFromCommittersStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/user/EmailSlackUserIdResolverTest.java
  src/test/java/jenkins/plugins/slack/workflow/MessageBuilderTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepIntegrationTest.java
  src/test/java/jenkins/plugins/slack/workflow/SlackSendStepTest.java
Labels: test, size/XL
